export default {
  appTitle: 'Note.SV',
  subtitle: "Nobody's got to know, Just by this minute",
  password: 'Passwords',
  settings: 'Settings',
  help: 'Help',
  note: 'Notes',
  balanceSatoshi: 'Balance: {walletBalance} Satoshi',
  charge: 'Add Fund',
  lockScreen: 'Lock Screen',
  inputPassword: 'Input password to unlock',
  BiometricAuth: 'Biometric Auth',
  FaceIDAuth: 'Use Face ID to auth and unlock',
  TouchIDAuth: 'Use Touch ID to auth and unlock',
  unlock: 'Unlock',
  forgotPassword: 'Forgot Password',
  day: 'Day',
  hours: 'Hours',
  minute: 'after {minute} minute',
  minutes: 'after {minute} minutes',
  seconds: 'Seconds',
  Characters: '{length} Characters',
  UppercaseLetters: 'Uppercase Letters (A-Z)',
  LowercaseLetters: 'Lowercase Letters (a-z)',
  IncludeNumbers: 'Include Numbers (0-9)',
  IncludeSymbols: 'Include Symbols',
  Intro: 'Introduce',
  CreateMasterWords: 'Create Master Words',
  ImportMasterWords: 'Import Master Words',
  ScanAndImportMasterWords: 'Scan QR Code of Master Code and Import',
  LockScreenPassword: 'Input Lock Screen Password',
  LockScreenPasswordAgain: 'Input Lock Screen Password again',
  error: 'You got an Error. Try it again soon please.',
  'At least one rule for pools must be true': 'At least one rule for pools must be true',
  'Generate Password': 'Generate Password',
  'App Version': 'App Version',
  'Auto Lock Screen': 'Auto Lock Screen',
  'Scroll back up': 'Scroll back up...',
  status: {
    0: 'Local',
    1: 'Broadcasted',
    2: 'Received',
    3: 'On Chain'
  },

  'History Record': 'History Record',
  Return: 'Back',
  Search: 'Look up',
  SearchAll: 'All',
  Share: 'Share(TODO)',
  'Sort By': 'Sort by',
  title: 'Title',
  time: 'Time',
  AddNote: 'Add a note',
  AddPassword: 'Add a password',
  AutoSaveDraft: 'Auto Save Draft',
  SaveDraft: 'Save Draft',
  SaveSubmit: 'Sync Save',
  Save: 'Save',
  RequireVal: 'Require input',
  Content: 'Content',
  CheckRule: 'Please check your input',
  Submited: 'Submited',
  EditNote: 'Edit',
  EditPassword: 'Edit',
  Delete: 'Delete',
  memo: 'Memo',
  Confirm: 'Confirm',
  ConfirmDelete: 'Delete note',
  ConfirmDraftDelete: 'Delete draft',
  fid: 'User ID or Email address',
  pwd: 'Password',
  url: 'Login URL Address',
  otp: 'One time password',
  Copied: 'Copied',
  'Copy Failed': 'Copy Failed',
  Edit: 'Edit',
  Close: 'Close',
  CloseHintForSaveDraft: 'Save it to draft？',
  Yes: 'Yes',
  No: 'No',
  UpdatedOn: 'Updated on',
  Settings: 'Settings',
  Language: 'Language',
  Account: 'Account',
  BackupMasterWords: 'Backup Master Words',
  ChangeLockPWD: 'Change Lockscreen Password',
  RemoveAccount: 'Remove Account',
  Remove: 'Remove',
  MasterWords: 'Master Words',
  Restart: 'Restart',
  Verify: 'Verify',
  VerifyMasterWords: 'Verify Master Words',
  MasterWordsVerified: 'Master Words is verified',
  MasterWordsFailed: 'Masteer Words is not verified, Please chceck again',
  ChangePassword: 'Change Lockscreen Password',
  InputNewPassword: 'New Password',
  InputPasswordAgain: 'New Password (input again)',
  Done: 'Done',
  MnemonicLanguage: 'The language of Master Words',
  PasswordFailed: 'Please check yopur password',
  PasswordChanged: 'Password was changed',
  ConfirmBackup: 'Confirm Backup',
  BackupMasterWordsNow: 'Backup Master Words now',
  SkipBackup: 'Backuped, Skip',
  Withdraw: 'Withdraw Satoshi',
  RequireCorrectAddress: 'Require a correct address',
  AddressFormat: 'Format',
  WithdrawAddress: 'Withdraw address',
  WithdrawAll: 'Withdraw all Satoshi',
  ContinueWithdraw: 'Continue Withdraw',
  'Skip this step': 'Skip this step',
  InputMissMasterWords: 'Please check your Master Words',
  ConfirmRemoveMessage: 'Confirm REMOVE. then create a new account or import Master Words',
  AddressMissing: 'Please check your address',
  Withdrawing: 'Withdrawing to <br/><span class="text-primary">{address}</span>',
  NoResults: 'No Result',
  NoPasswordMessage: 'There is no password message',
  NoNoteMessage: 'There is no note message',
  Alipay: 'Alipay',
  Wechatpay: 'Wechat Pay',
  Unionpay: 'Union Pay',
  'Money Button': 'Money Button',
  Wallet: 'Bitcoin SV Wallet',
  ChargeAddress: 'Charge Address',
  ChargeAmount: 'Charge Amount',
  USD: 'USD',
  RMB: 'RMB',
  'No Balance': 'No balance of Satoshi, Please add fund',

  IntroMessage: `<p>
  NoteSV use the highest level of security technology to keep your personal data, such as passwords, bank accounts and other confidential information.
</p>
<p>
All the content is encrypted using an elliptic curve asymmetric encryption algorithm, which is held in thousands of Bitcoin nodes around the world. Only you can see the contents, no one can peek. Data will never be lost due to a computer failure.
</p>
<p>
First, you need to create a master secret words and record it with a <strong> pen and paper </strong>. Master words is the only key for you to access the information, once lost and cannot be recovered, please do not take screenshots when recording master words.
</p>`,

  MasterWordsMessage: `<p>
  Please use paper and pen to record the master words in order and keep them safe. Master words is the only key for you to access information, once lost and unable to recover, do not record the super password screenshot, the loss of the picture leads to data loss or theft.
</p>`,

  InputMasterWordsMessage: `<p>
  Please enter the your master words in sequence, and then click the verify button.
</p>
`,
  BackupMessage: `<p>
  Have you backed up the master words? If not backup will not be able to recover this account.
</p>`,
  InputAddressMessage: `<p>
  Enter your BSV wallet address, or the exchange address, and double check that it is correct. Click the withdraw button and withdraw all Satoshi.
</p>`,
  InputAddressHintMessage: `<p>
  If you have already backed up your account, you do not need to withdraw Satoshi. The next time through the master words to restore the account can be used.
</p>
`,
  ChargeMessage: `
<p>
The software costs a little Satoshi to use. when you recharge $10 to account that is equivalent to writing more than 3,000 secure documents.
    </p>

    <p>Please select the amount and method of charge</p>
`,
  ChargeWalletMessage: `<p>
  If you already have a BSV you can send some to the above address. If you don't have BSV, please charge by other methods.
</p>
`,
  PasswordError: 'Password Error.',
  ForgotPasswordTitle: 'Forgot password really?',
  ForgotPasswordMessage: 'Please reset then import the backuped Master Words to restore system.',
  Cancel: 'Cancel',
  ResetSystem: 'Reset System',
  ChargeSVCafeMessage: 'SV Cafe support Wechat Pay and Alipay for charging. Please choose amount and click icon button.',
  'SV Cafe': 'SV Cafe',
  ChargeMoneyButtonMessage: 'Money Button is the simplest payment system to charge Satoshi. If you have a Money Button account, choose amount then slide button, please',
  'Image Files': 'Image Files',
  'Clear All': 'Clear All',
  'Attach your files': 'Attach your image files',
  nFiles: '{count} Files. ({size}) Max total {maxTotalSize} available',
  'Pick Files': 'Pick Files',
  Satoshi: ' Satoshi',
  'Dot Wallet': 'Dot Wallet',
  ChargeDotWalletMessage: 'DotWallet is the most used worldwide BSV wallet. it provide secure and reliable digital asset management services to millions of users in more than 150 countries around the world. Please choose amount and click icon button.',
  ChargeFails: 'Fail to charge, Please use other method',
  'checking-for-update': 'Checking for update...',
  'update-available': 'Update available. Auto Download...',
  'update-not-available': 'Update not available.',
  'update-downloaded': 'Update downloaded',
  'update-error': 'Error in update.',
  Syncing: 'Syncing records',
  SyncFinished: 'Sync finished',
  Paymail: 'Paymail Account',
  PaymailDesc: 'Only for your ID of NoteSV, DONT send email to this address.',
  NoPaymal: 'Not Set',
  NoLock: 'Never Lock',
  Online: 'Internet online',
  Offline: 'Internet offline',
  AccountID: 'Account ID',
  Name: 'Name',
  Email: 'Email address',
  CheckAccountID: 'Check ID',
  SaveAccount: 'Save Account',
  AliasNoModify: "Once saved, the account ID can't be modified",
  'id-already-exist': 'The ID already exist',
  'id-available': 'The ID is available',
  RequireAliasRule: 'Require input alphanumeric',
  ServiceUnavailable: 'Service is unavailable now',
  Saved: 'Saved',
  PaymailAddress: 'Paymail Address',
  PaymailAddressMessage: 'OR, you also recharge BSV Satoshi to your Paimail address.',
  NoPaymailAddressMessage: 'Register an account for more easy recharge',
  RegisterAccoun: 'Register',
  'exceed-max-total-size': 'Exceeds the max uploadable size (Total Max:{maxSize})',
  ChangePhoto: 'Change Photo',
  Minimize: 'Minimize',
  Maximize: 'Maximize',
  Reset: 'Reset',
  ChargeAlipayWechatMessage: 'SV Cafe support Wechat Pay and Alipay for charging. Please choose amount and click icon button, then scan QR Code via Smartphone App.',
  Charged: 'You have now successfully recharged',
  ChargeTimeout: 'Recharge Timeout, Please try again',
  ResizeImage: 'Auto resize image',
  DeleteDraft: 'Discard Draft',
  LockNow: 'Lock now',
  RegisterAccount: 'Register Account'
}
